<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use App\Models\Yard;
use App\Models\User;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminUser = User::where('email', 'admin@example.com')->first();
        $mainYard = Yard::where('yard_type', 'main_yard')->first();
        $shop = Yard::where('yard_type', 'shop')->first();

        $vehicles = [
            // Dump Trucks
            [
                'name' => 'Mack Granite Dump Truck #1',
                'vehicle_number' => 'DT-001',
                'qr_code' => 'VEH-DT001',
                'vin' => '1M2AG11C9HM123456',
                'license_plate' => 'AZ-DT1234',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(8),
                'year' => 2019,
                'make' => 'Mack',
                'model' => 'Granite GU813',
                'color' => 'Red',
                'vehicle_type' => 'dump_truck',
                'fuel_type' => 'diesel',
                'tank_capacity_gallons' => 100.0,
                'weight_class' => 'Class 8',
                'gvwr_pounds' => 80000,
                'towing_capacity_pounds' => 5000,
                'current_odometer_miles' => 87543.2,
                'requires_cdl' => true,
                'requires_dot_inspection' => true,
                'last_dot_inspection_date' => Carbon::now()->subMonths(10),
                'next_dot_inspection_due' => Carbon::now()->addMonths(2),
                'insurance_policy_number' => 'POL-DT-001',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'active',
                'current_location_type' => 'yard',
                'current_location_id' => $mainYard->id,
                'current_location_gps_lat' => $mainYard->gps_latitude,
                'current_location_gps_lng' => $mainYard->gps_longitude,
                'description' => 'Heavy-duty tri-axle dump truck, 16 cubic yard capacity',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],
            [
                'name' => 'Kenworth T800 Dump Truck #2',
                'vehicle_number' => 'DT-002',
                'qr_code' => 'VEH-DT002',
                'vin' => '1NKDL40X1TJ123457',
                'license_plate' => 'AZ-DT5678',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(6),
                'year' => 2020,
                'make' => 'Kenworth',
                'model' => 'T800',
                'color' => 'White',
                'vehicle_type' => 'dump_truck',
                'fuel_type' => 'diesel',
                'tank_capacity_gallons' => 120.0,
                'weight_class' => 'Class 8',
                'gvwr_pounds' => 80000,
                'towing_capacity_pounds' => 5000,
                'current_odometer_miles' => 65234.7,
                'requires_cdl' => true,
                'requires_dot_inspection' => true,
                'last_dot_inspection_date' => Carbon::now()->subMonths(8),
                'next_dot_inspection_due' => Carbon::now()->addMonths(4),
                'insurance_policy_number' => 'POL-DT-002',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'active',
                'current_location_type' => 'yard',
                'current_location_id' => $mainYard->id,
                'current_location_gps_lat' => $mainYard->gps_latitude,
                'current_location_gps_lng' => $mainYard->gps_longitude,
                'description' => 'Heavy-duty tri-axle dump truck with electric tarp',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],

            // Concrete Mixers
            [
                'name' => 'Peterbilt 365 Mixer Truck',
                'vehicle_number' => 'MX-001',
                'qr_code' => 'VEH-MX001',
                'vin' => '1NPHDXDX1TD123458',
                'license_plate' => 'AZ-MX1111',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(9),
                'year' => 2018,
                'make' => 'Peterbilt',
                'model' => '365 Mixer',
                'color' => 'Yellow',
                'vehicle_type' => 'concrete_mixer',
                'fuel_type' => 'diesel',
                'tank_capacity_gallons' => 100.0,
                'weight_class' => 'Class 8',
                'gvwr_pounds' => 66000,
                'current_odometer_miles' => 112345.3,
                'requires_cdl' => true,
                'requires_dot_inspection' => true,
                'last_dot_inspection_date' => Carbon::now()->subMonths(6),
                'next_dot_inspection_due' => Carbon::now()->addMonths(6),
                'insurance_policy_number' => 'POL-MX-001',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'maintenance',
                'current_location_type' => 'yard',
                'current_location_id' => $shop->id,
                'current_location_gps_lat' => $shop->gps_latitude,
                'current_location_gps_lng' => $shop->gps_longitude,
                'description' => '10 cubic yard front discharge mixer',
                'notes' => 'Drum bearing replacement in progress',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],

            // Pickup Trucks
            [
                'name' => 'Ford F-350 Crew Cab #1',
                'vehicle_number' => 'PU-001',
                'qr_code' => 'VEH-PU001',
                'vin' => '1FT8W3DT6LEA12345',
                'license_plate' => 'AZ-PU2345',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(10),
                'year' => 2021,
                'make' => 'Ford',
                'model' => 'F-350 Super Duty',
                'color' => 'White',
                'vehicle_type' => 'pickup',
                'fuel_type' => 'diesel',
                'tank_capacity_gallons' => 48.0,
                'weight_class' => 'Class 3',
                'gvwr_pounds' => 14000,
                'towing_capacity_pounds' => 21000,
                'current_odometer_miles' => 34567.8,
                'requires_cdl' => false,
                'requires_dot_inspection' => false,
                'insurance_policy_number' => 'POL-PU-001',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'active',
                'current_location_type' => 'yard',
                'current_location_id' => $mainYard->id,
                'current_location_gps_lat' => $mainYard->gps_latitude,
                'current_location_gps_lng' => $mainYard->gps_longitude,
                'assigned_to_user_id' => $adminUser->id,
                'description' => 'Foreman truck with service body and tool storage',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],
            [
                'name' => 'RAM 2500 Crew Cab #2',
                'vehicle_number' => 'PU-002',
                'qr_code' => 'VEH-PU002',
                'vin' => '3C6UR5DL3MG123459',
                'license_plate' => 'AZ-PU6789',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(7),
                'year' => 2022,
                'make' => 'RAM',
                'model' => '2500 Big Horn',
                'color' => 'Blue',
                'vehicle_type' => 'pickup',
                'fuel_type' => 'gasoline',
                'tank_capacity_gallons' => 32.0,
                'weight_class' => 'Class 2B',
                'gvwr_pounds' => 10000,
                'towing_capacity_pounds' => 17540,
                'current_odometer_miles' => 18234.2,
                'requires_cdl' => false,
                'requires_dot_inspection' => false,
                'insurance_policy_number' => 'POL-PU-002',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'active',
                'current_location_type' => 'yard',
                'current_location_id' => $mainYard->id,
                'current_location_gps_lat' => $mainYard->gps_latitude,
                'current_location_gps_lng' => $mainYard->gps_longitude,
                'description' => 'General purpose crew truck',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],

            // Flatbed Trucks
            [
                'name' => 'International Flatbed Truck',
                'vehicle_number' => 'FB-001',
                'qr_code' => 'VEH-FB001',
                'vin' => '1HTMMAAN6JH123450',
                'license_plate' => 'AZ-FB1234',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(5),
                'year' => 2017,
                'make' => 'International',
                'model' => 'DuraStar 4300',
                'color' => 'White',
                'vehicle_type' => 'flatbed',
                'fuel_type' => 'diesel',
                'tank_capacity_gallons' => 60.0,
                'weight_class' => 'Class 6',
                'gvwr_pounds' => 33000,
                'towing_capacity_pounds' => 10000,
                'current_odometer_miles' => 145678.5,
                'requires_cdl' => true,
                'requires_dot_inspection' => true,
                'last_dot_inspection_date' => Carbon::now()->subMonths(9),
                'next_dot_inspection_due' => Carbon::now()->addMonths(3),
                'insurance_policy_number' => 'POL-FB-001',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'active',
                'current_location_type' => 'yard',
                'current_location_id' => $mainYard->id,
                'current_location_gps_lat' => $mainYard->gps_latitude,
                'current_location_gps_lng' => $mainYard->gps_longitude,
                'description' => '20ft flatbed with liftgate for equipment transport',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],

            // Lowboy Trailer
            [
                'name' => 'Trail King Lowboy Trailer',
                'vehicle_number' => 'LB-001',
                'qr_code' => 'VEH-LB001',
                'vin' => '1TKL560X0EJ123451',
                'license_plate' => 'AZ-LB5678',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(8),
                'year' => 2019,
                'make' => 'Trail King',
                'model' => 'TK70HT',
                'color' => 'Black',
                'vehicle_type' => 'lowboy',
                'fuel_type' => null,
                'weight_class' => 'Trailer',
                'gvwr_pounds' => 70000,
                'current_odometer_miles' => 0,
                'requires_cdl' => true,
                'requires_dot_inspection' => true,
                'last_dot_inspection_date' => Carbon::now()->subMonths(7),
                'next_dot_inspection_due' => Carbon::now()->addMonths(5),
                'insurance_policy_number' => 'POL-LB-001',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'active',
                'current_location_type' => 'yard',
                'current_location_id' => $mainYard->id,
                'current_location_gps_lat' => $mainYard->gps_latitude,
                'current_location_gps_lng' => $mainYard->gps_longitude,
                'description' => '70-ton lowboy trailer for heavy equipment transport',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],

            // Service Truck
            [
                'name' => 'Ford F-550 Service Truck',
                'vehicle_number' => 'ST-001',
                'qr_code' => 'VEH-ST001',
                'vin' => '1FDUF5GY3MEA12345',
                'license_plate' => 'AZ-ST9012',
                'registration_state' => 'AZ',
                'registration_expiration' => Carbon::now()->addMonths(9),
                'year' => 2021,
                'make' => 'Ford',
                'model' => 'F-550 Super Duty',
                'color' => 'Yellow',
                'vehicle_type' => 'service_truck',
                'fuel_type' => 'diesel',
                'tank_capacity_gallons' => 40.0,
                'weight_class' => 'Class 5',
                'gvwr_pounds' => 19500,
                'current_odometer_miles' => 28456.3,
                'requires_cdl' => false,
                'requires_dot_inspection' => false,
                'insurance_policy_number' => 'POL-ST-001',
                'insurance_provider' => 'State Farm Commercial',
                'insurance_expiration' => Carbon::now()->addMonths(11),
                'status' => 'active',
                'current_location_type' => 'yard',
                'current_location_id' => $shop->id,
                'current_location_gps_lat' => $shop->gps_latitude,
                'current_location_gps_lng' => $shop->gps_longitude,
                'description' => 'Field service truck with mechanic body, air compressor, and welder',
                'created_by' => $adminUser->id,
                'updated_by' => $adminUser->id,
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            Vehicle::create($vehicleData);
        }

        $this->command->info('Vehicles seeded successfully!');
    }
}
